name: Deploy to the server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: GitHub Runner IP
        run: echo "$(curl -s https://api.ipify.org)"

      - name: SSH Deploy
        uses: easingthemes/ssh-deploy@main
        with:
          ARGS: >-
            --recursive
            --links
            --group
            --owner
            --devices
            --specials
            --compress
            --verbose
            --checksum
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: "92.53.96.13"
          REMOTE_USER: "aisteron"
          TARGET: "/home/a/aisteron/wordpress/public_html/wp-content/"
          EXCLUDE: "/upgrade/, /uploads/, /.git/, /.github/, .gitignore"
