name: Test SSH Connection

on:
  workflow_dispatch: # Запуск вручную из интерфейса GitHub Actions

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Check SSH connection
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: "vh374.timeweb.ru"
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          SCRIPT_BEFORE: |
            echo "=== SSH Connection Successful ==="
            whoami
            hostname
